# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-24 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_games_v1', '0003_auto_20170324_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
